language: php

php:
    - 5.3
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update || true
    - composer install --dev --prefer-dist

script:
    - bin/atoum -d tests/units

notifications:
    email:
        - ci@verylastroom.com
